version: '3'

services:
  postgres:
    image: 'postgres:13'
    container_name: 'image-postgres'
    ports:
      - 5433:5432
    environment:
      - 'POSTGRES_USER=sa'
      - 'POSTGRES_PASSWORD=password'
      - 'POSTGRES_DB=imagedb'